"""autogenerated by genmsg_py from NavData.msg. Do not edit."""
import roslib.message
import struct


class NavData(roslib.message.Message):
  _md5sum = "52f35305128af01a37ee8cd90d1f5912"
  _type = "ardrone_emulator/NavData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint16 tag
uint16 size
uint32 ctrlState
uint32 batLevel
float32 theta
float32 phi
float32 psi
int32 altitude
float32 vx
float32 vy
float32 vz
uint32 numFrames

"""
  __slots__ = ['tag','size','ctrlState','batLevel','theta','phi','psi','altitude','vx','vy','vz','numFrames']
  _slot_types = ['uint16','uint16','uint32','uint32','float32','float32','float32','int32','float32','float32','float32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       tag,size,ctrlState,batLevel,theta,phi,psi,altitude,vx,vy,vz,numFrames
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(NavData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.tag is None:
        self.tag = 0
      if self.size is None:
        self.size = 0
      if self.ctrlState is None:
        self.ctrlState = 0
      if self.batLevel is None:
        self.batLevel = 0
      if self.theta is None:
        self.theta = 0.
      if self.phi is None:
        self.phi = 0.
      if self.psi is None:
        self.psi = 0.
      if self.altitude is None:
        self.altitude = 0
      if self.vx is None:
        self.vx = 0.
      if self.vy is None:
        self.vy = 0.
      if self.vz is None:
        self.vz = 0.
      if self.numFrames is None:
        self.numFrames = 0
    else:
      self.tag = 0
      self.size = 0
      self.ctrlState = 0
      self.batLevel = 0
      self.theta = 0.
      self.phi = 0.
      self.psi = 0.
      self.altitude = 0
      self.vx = 0.
      self.vy = 0.
      self.vz = 0.
      self.numFrames = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_2H2I3fi3fI.pack(_x.tag, _x.size, _x.ctrlState, _x.batLevel, _x.theta, _x.phi, _x.psi, _x.altitude, _x.vx, _x.vy, _x.vz, _x.numFrames))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 44
      (_x.tag, _x.size, _x.ctrlState, _x.batLevel, _x.theta, _x.phi, _x.psi, _x.altitude, _x.vx, _x.vy, _x.vz, _x.numFrames,) = _struct_2H2I3fi3fI.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_2H2I3fi3fI.pack(_x.tag, _x.size, _x.ctrlState, _x.batLevel, _x.theta, _x.phi, _x.psi, _x.altitude, _x.vx, _x.vy, _x.vz, _x.numFrames))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 44
      (_x.tag, _x.size, _x.ctrlState, _x.batLevel, _x.theta, _x.phi, _x.psi, _x.altitude, _x.vx, _x.vy, _x.vz, _x.numFrames,) = _struct_2H2I3fi3fI.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_2H2I3fi3fI = struct.Struct("<2H2I3fi3fI")
